name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        nim: ["binary:stable", "binary:1.6.18"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nim }}
    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
